// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3wmG7B0CCGdRddeK3ivKLgaXaEh8djGI',
    appId: '1:573721059813:web:646b1435b9d4c8506ccf0c',
    messagingSenderId: '573721059813',
    projectId: 'bookswap-app-86346',
    authDomain: 'bookswap-app-86346.firebaseapp.com',
    storageBucket: 'bookswap-app-86346.firebasestorage.app',
    measurementId: 'G-921RKLH2RQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD80HnIWBY-RQy1jYOebOdTCnhbAC_B8fs',
    appId: '1:573721059813:android:fc246354886b6d576ccf0c',
    messagingSenderId: '573721059813',
    projectId: 'bookswap-app-86346',
    storageBucket: 'bookswap-app-86346.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo9S-aaCKGU5k4Ahnv068-i1_yZ5gXUs4',
    appId: '1:573721059813:ios:9ba435d5547435616ccf0c',
    messagingSenderId: '573721059813',
    projectId: 'bookswap-app-86346',
    storageBucket: 'bookswap-app-86346.firebasestorage.app',
    iosBundleId: 'com.example.bookswapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBo9S-aaCKGU5k4Ahnv068-i1_yZ5gXUs4',
    appId: '1:573721059813:ios:9ba435d5547435616ccf0c',
    messagingSenderId: '573721059813',
    projectId: 'bookswap-app-86346',
    storageBucket: 'bookswap-app-86346.firebasestorage.app',
    iosBundleId: 'com.example.bookswapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3wmG7B0CCGdRddeK3ivKLgaXaEh8djGI',
    appId: '1:573721059813:web:1532cd236678733f6ccf0c',
    messagingSenderId: '573721059813',
    projectId: 'bookswap-app-86346',
    authDomain: 'bookswap-app-86346.firebaseapp.com',
    storageBucket: 'bookswap-app-86346.firebasestorage.app',
    measurementId: 'G-30P4EJ9674',
  );

}